### ISSUE TITLE
Compiler errors (Copy constraint on `Buffer`)

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/hematite#181]
The methods on `Cell` requires a `Copy` constraint, which is no longer implemented by `Buffer`.

```
src/chunk.rs:113:40: 113:45 error: type `&core::cell::Cell<core::option::Option<shader::Buffer>>` does not implement any method in scope named `get`
src/chunk.rs:113                 f(x, y as i32, z, c, b.get())
                                                        ^~~~~
src/chunk.rs:113:45: 113:45 help: methods from traits can only be called if the trait is implemented and in scope; the following traits define a method `get`, perhaps you need to implement one of them:
src/chunk.rs:113:45: 113:45 help: candidate #1: `core::slice::SliceExt`
src/chunk.rs:113:45: 113:45 help: candidate #2: `collections::slice::SliceExt`
src/chunk.rs:113:45: 113:45 help: candidate #3: `quack::get::Get`
src/minecraft/region.rs:143:41: 143:50 error: the trait `core::marker::Copy` is not implemented for the type `shader::Buffer` [E0277]
src/minecraft/region.rs:143             buffers: Array::from_fn(|_| Cell::new(None)),
                                                                    ^~~~~~~~~
src/main.rs:294:38: 294:43 error: type `&core::cell::Cell<core::option::Option<shader::Buffer>>` does not implement any method in scope named `get`
src/main.rs:294                         match buffer.get() {
                                                     ^~~~~
src/main.rs:294:43: 294:43 help: methods from traits can only be called if the trait is implemented and in scope; the following traits define a method `get`, perhaps you need to implement one of them:
src/main.rs:294:43: 294:43 help: candidate #1: `core::slice::SliceExt`
src/main.rs:294:43: 294:43 help: candidate #2: `collections::slice::SliceExt`
src/main.rs:294:43: 294:43 help: candidate #3: `quack::get::Get`
src/main.rs:302:32: 304:27 error: type `&core::cell::Cell<core::option::Option<shader::Buffer>>` does not implement any method in scope named `set`
src/main.rs:302                         buffer.set(Some(
src/main.rs:303                             renderer.create_buffer(staging_buffer.as_slice())
src/main.rs:304                         ));
src/main.rs:304:27: 304:27 help: methods from traits can only be called if the trait is implemented and in scope; the following trait defines a method `set`, perhaps you need to implement it:
src/main.rs:304:27: 304:27 help: candidate #1: `quack::set::Set`
error: aborting due to 4 previous errors
Could not compile `hematite`.
```

**Comment by bvssvni** [comment]
The PR that broke it in Gfx was https://github.com/gfx-rs/gfx-rs/pull/507

**Comment by bvssvni** [comment]
https://github.com/sectopod/gfx-rs/commit/7de1690687135ff30424dff1b39990dbad574215#diff-9727ac41ee298b338aa97b20cd10c264L204

**Comment by bvssvni** [comment]
No, I was wrong. The `Copy` constraint was moved here https://github.com/sectopod/gfx-rs/commit/7de1690687135ff30424dff1b39990dbad574215#diff-9727ac41ee298b338aa97b20cd10c264R214

**Comment by bvssvni** [comment]
The problem is that `Copy` is implemented with a `where` constraint.

I guess, somehow the `<ShaderParam as gfx::shade::ShaderParam>::Link` is not `Copy`.

**Comment by eddyb** [comment]
There should be a rust issue about deriving not working correctly with associated types.

**Comment by toqueteos** [comment]
Dup of #170 ?

**Comment by bvssvni** [comment]
@eddyb Are you suspicious about this being a bug in Rust?

**Comment by eddyb** [comment]
It's a known issue, and I expect there to an issue open on it in the Rust repo.

**Comment by bvssvni** [comment]
See https://github.com/rust-lang/rust/pull/21237

**Comment by kvark** [comment]
I'll deal with it tonight, unless it's fixed by then.

**Comment by kvark** [comment]
This should be fixed in latest, but the new gfx-rs version has not yet been published.

**Comment by kvark** [comment]
Gfx v0.1.2 has been published. Please try again with `cargo update`.

**Comment by toqueteos** [comment]
I just tried on windows. Same outcome thing as before.

**Comment by kvark** [comment]
Thanks @toqueteos ! I'll have a closer look at this when I'm back at home. We do have the `Copy` implemented now, and there is even a test for it, so I find it strange that the error is still there.

**Comment by toqueteos** [comment]
You're welcome @kvark! Just in case I also tried with a fresh clone in a different folder but still no luck. Same 4 nasty errors.

**Comment by kvark** [comment]
I think I found something. Here is your struct:
```rust
pub struct Buffer {
    buf: gfx::BufferHandle<Vertex>,
    batch: gfx::batch::RefBatch<ShaderParam>,
}
```
So even if both gfx parts are `Copy`, it doesn't make `Copy` implemented for your `Buffer` by default. I think you are just missing `#[derive(Copy)]` for it.

**Comment by toqueteos** [comment]
Totally right, I forgot to add the missing derive Copy. It does indeed compile again! Let me copy the MC assets and make a screenshot!! YAY :+1: for @kvark

**Comment by kvark** [comment]
Thanks! Closing as fixed.

**Comment by bvssvni** [comment]
This needs a PR, but mac nightlies are delayed so I can't fix it now.

**Comment by toqueteos** [comment]
@bvssvni Working my ass off on it, also fixing loads of stuff.
